export default {
  defaultTempo: 120,
  minTempo: 30,
  maxTempo: 240,
  defaultOctave: 5,
  minOctave: 0,
  maxOctave: 8,
  defaultNoteLength: 4,
  minNoteLength: 1,
  maxNoteLength: 64,
  defaultQuantize: 6,
  minQuantize: 0,
  maxQuantize: 8,
  defaultVolume:  12,
  minVolume: 0,
  maxVolume: 16,
  defaultLoopCount: 2,
  maxLoopCount: 999,
  octaveShiftDirection: 1
};
